/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const LeadForm = IDL.Record({
  'id' : IDL.Nat,
  'contactTime' : IDL.Opt(IDL.Text),
  'propertyType' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'visitDate' : IDL.Opt(IDL.Text),
  'formType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'priceDisplay' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const LeadFormInput = IDL.Record({
  'contactTime' : IDL.Opt(IDL.Text),
  'propertyType' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'visitDate' : IDL.Opt(IDL.Text),
  'formType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getLeads' : IDL.Func([], [IDL.Vec(LeadForm)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getPropertiesByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'getPropertyById' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'submitLead' : IDL.Func([LeadFormInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const LeadForm = IDL.Record({
    'id' : IDL.Nat,
    'contactTime' : IDL.Opt(IDL.Text),
    'propertyType' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'visitDate' : IDL.Opt(IDL.Text),
    'formType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'priceDisplay' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const LeadFormInput = IDL.Record({
    'contactTime' : IDL.Opt(IDL.Text),
    'propertyType' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'visitDate' : IDL.Opt(IDL.Text),
    'formType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getLeads' : IDL.Func([], [IDL.Vec(LeadForm)], ['query']),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getPropertiesByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertyById' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'submitLead' : IDL.Func([LeadFormInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };