/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeadForm {
  'id' : bigint,
  'contactTime' : [] | [string],
  'propertyType' : [] | [string],
  'name' : string,
  'visitDate' : [] | [string],
  'formType' : string,
  'email' : string,
  'message' : [] | [string],
  'timestamp' : Timestamp,
  'phone' : string,
  'budget' : [] | [string],
  'location' : [] | [string],
}
export interface LeadFormInput {
  'contactTime' : [] | [string],
  'propertyType' : [] | [string],
  'name' : string,
  'visitDate' : [] | [string],
  'formType' : string,
  'email' : string,
  'message' : [] | [string],
  'phone' : string,
  'budget' : [] | [string],
  'location' : [] | [string],
}
export interface Property {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'propertyType' : string,
  'bedrooms' : bigint,
  'area' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'amenities' : Array<string>,
  'imageUrl' : string,
  'priceDisplay' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getLeads' : ActorMethod<[], Array<LeadForm>>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getPropertiesByIds' : ActorMethod<[Array<bigint>], Array<Property>>,
  'getPropertiesByLocation' : ActorMethod<[string], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[string], Array<Property>>,
  'getPropertyById' : ActorMethod<[bigint], [] | [Property]>,
  'submitLead' : ActorMethod<[LeadFormInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];