/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: bigint;
    status: string;
    title: string;
    propertyType: string;
    bedrooms: bigint;
    area: bigint;
    tags: Array<string>;
    description: string;
    amenities: Array<string>;
    imageUrl: string;
    priceDisplay: string;
    bathrooms: bigint;
    price: bigint;
    location: string;
}
export type Timestamp = bigint;
export interface LeadFormInput {
    contactTime?: string;
    propertyType?: string;
    name: string;
    visitDate?: string;
    formType: string;
    email: string;
    message?: string;
    phone: string;
    budget?: string;
    location?: string;
}
export interface LeadForm {
    id: bigint;
    contactTime?: string;
    propertyType?: string;
    name: string;
    visitDate?: string;
    formType: string;
    email: string;
    message?: string;
    timestamp: Timestamp;
    phone: string;
    budget?: string;
    location?: string;
}
export interface backendInterface {
    getLeads(): Promise<Array<LeadForm>>;
    getProperties(): Promise<Array<Property>>;
    getPropertiesByIds(ids: Array<bigint>): Promise<Array<Property>>;
    getPropertiesByLocation(location: string): Promise<Array<Property>>;
    getPropertiesByType(propertyType: string): Promise<Array<Property>>;
    getPropertyById(id: bigint): Promise<Property | null>;
    submitLead(input: LeadFormInput): Promise<bigint>;
}
import type { LeadForm as _LeadForm, LeadFormInput as _LeadFormInput, Property as _Property, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getLeads(): Promise<Array<LeadForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperties();
            return result;
        }
    }
    async getPropertiesByIds(arg0: Array<bigint>): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByIds(arg0);
            return result;
        }
    }
    async getPropertiesByLocation(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByLocation(arg0);
            return result;
        }
    }
    async getPropertiesByType(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByType(arg0);
            return result;
        }
    }
    async getPropertyById(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyById(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyById(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLead(arg0: LeadFormInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(to_candid_LeadFormInput_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(to_candid_LeadFormInput_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_LeadForm_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadForm): LeadForm {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Property | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactTime: [] | [string];
    propertyType: [] | [string];
    name: string;
    visitDate: [] | [string];
    formType: string;
    email: string;
    message: [] | [string];
    timestamp: _Timestamp;
    phone: string;
    budget: [] | [string];
    location: [] | [string];
}): {
    id: bigint;
    contactTime?: string;
    propertyType?: string;
    name: string;
    visitDate?: string;
    formType: string;
    email: string;
    message?: string;
    timestamp: Timestamp;
    phone: string;
    budget?: string;
    location?: string;
} {
    return {
        id: value.id,
        contactTime: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.contactTime)),
        propertyType: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.propertyType)),
        name: value.name,
        visitDate: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.visitDate)),
        formType: value.formType,
        email: value.email,
        message: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.message)),
        timestamp: value.timestamp,
        phone: value.phone,
        budget: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.budget)),
        location: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadForm>): Array<LeadForm> {
    return value.map((x)=>from_candid_LeadForm_n2(_uploadFile, _downloadFile, x));
}
function to_candid_LeadFormInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadFormInput): _LeadFormInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactTime?: string;
    propertyType?: string;
    name: string;
    visitDate?: string;
    formType: string;
    email: string;
    message?: string;
    phone: string;
    budget?: string;
    location?: string;
}): {
    contactTime: [] | [string];
    propertyType: [] | [string];
    name: string;
    visitDate: [] | [string];
    formType: string;
    email: string;
    message: [] | [string];
    phone: string;
    budget: [] | [string];
    location: [] | [string];
} {
    return {
        contactTime: value.contactTime ? candid_some(value.contactTime) : candid_none(),
        propertyType: value.propertyType ? candid_some(value.propertyType) : candid_none(),
        name: value.name,
        visitDate: value.visitDate ? candid_some(value.visitDate) : candid_none(),
        formType: value.formType,
        email: value.email,
        message: value.message ? candid_some(value.message) : candid_none(),
        phone: value.phone,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
